package com.example.core.network.utils

object HttpCodes {
    const val REQUEST_NONE = 0
    const val REQUEST_CONTINUE = 100
    const val REQUEST_SWITCHING_PROTOCOLS = 101
    const val REQUEST_PROCESSING = 102
    const val REQUEST_EARLY_HINTS = 103
    const val REQUEST_SUCCESS = 200
    const val REQUEST_CREATED = 201
    const val REQUEST_ACCEPTED = 202
    const val REQUEST_NON_AUTHORITATIVE_INFORMATION = 203
    const val REQUEST_NO_CONTENT = 204
    const val REQUEST_RESET_CONTENT = 205
    const val REQUEST_PARTIAL_CONTENT = 206
    const val REQUEST_MULTI_STATUS = 207
    const val REQUEST_ALREADY_REPORTED = 208
    const val REQUEST_IM_USED = 226
    const val REQUEST_MULTIPLE_CHOICES = 300
    const val REQUEST_MOVED_PERMANENTLY = 301
    const val REQUEST_FOUND = 302
    const val REQUEST_SEE_OTHER = 303
    const val REQUEST_NOT_MODIFIED = 304
    const val REQUEST_USE_PROXY = 305
    const val REQUEST_TEMPORARY_REDIRECT = 307
    const val REQUEST_PERMANENT_REDIRECT = 308
    const val REQUEST_BAD_REQUEST = 400
    const val REQUEST_UNAUTHORIZED = 401
    const val REQUEST_PAYMENT_REQUIRED = 402
    const val REQUEST_FORBIDDEN_REQUEST = 403
    const val REQUEST_NOT_FOUND = 404
    const val REQUEST_METHOD_NOT_ALLOWED = 405
    const val REQUEST_NOT_ACCEPTABLE = 406
    const val REQUEST_PROXY_AUTHENTICATION_REQUIRED = 407
    const val REQUEST_REQUEST_TIMEOUT = 408
    const val REQUEST_CONFLICT = 409
    const val REQUEST_GONE = 410
    const val REQUEST_LENGTH_REQUIRED = 411
    const val REQUEST_PRECONDITION_FAILED = 412
    const val REQUEST_PAYLOAD_TOO_LARGE = 413
    const val REQUEST_URI_TOO_LONG = 414
    const val REQUEST_UNSUPPORTED_MEDIA_TYPE = 415
    const val REQUEST_RANGE_NOT_SATISFIABLE = 416
    const val REQUEST_EXPECTATION_FAILED = 417
    const val REQUEST_IM_A_TEAPOT = 418
    const val REQUEST_MISDIRECTED_REQUEST = 421
    const val REQUEST_UNPROCESSABLE_ENTITY = 422
    const val REQUEST_LOCKED = 423
    const val REQUEST_FAILED_DEPENDENCY = 424
    const val REQUEST_TOO_EARLY = 425
    const val REQUEST_UPGRADE_REQUIRED = 426
    const val REQUEST_PRECONDITION_REQUIRED = 428
    const val REQUEST_TOO_MANY_REQUESTS = 429
    const val REQUEST_REQUEST_HEADER_FIELDS_TOO_LARGE = 431
    const val REQUEST_UNAVAILABLE_FOR_LEGAL_REASONS = 451
    const val REQUEST_INTERNAL_SERVER_ERROR = 500
    const val REQUEST_NOT_IMPLEMENTED = 501
    const val REQUEST_BAD_GATEWAY = 502
    const val REQUEST_SERVICE_UNAVAILABLE = 503
    const val REQUEST_GATEWAY_TIMEOUT = 504
    const val REQUEST_HTTP_VERSION_NOT_SUPPORTED = 505
    const val REQUEST_VARIANT_ALSO_NEGOTIATES = 506
    const val REQUEST_INSUFFICIENT_STORAGE = 507
    const val REQUEST_LOOP_DETECTED = 508
    const val REQUEST_NOT_EXTENDED = 510
    const val REQUEST_NETWORK_AUTHENTICATION_REQUIRED = 511
}

// Http methods
enum class HttpMethod(val method: String) {
    GET("GET"),
    POST("POST"),
    PUT("PUT"),
    DELETE("DELETE"),
    PATCH("PATCH")
}